import type { MetadataRoute } from "next";
import { DISALLOWED_PATHS, SITE_URL } from "@/lib/site-routes";

/**
 * Standards-compliant robots.txt generated by Next.js Metadata Routes.
 *
 * - Allows all public content for every crawler (Googlebot, Bingbot,
 *   plus AI crawlers like GPTBot, ClaudeBot, PerplexityBot, etc.).
 * - Blocks internal API routes, preview/admin/internal segments, and
 *   the dev-only og-preview tooling.
 * - Points to the canonical sitemap so crawlers can discover every
 *   published URL without scraping.
 */
export default function robots(): MetadataRoute.Robots {
  return {
    rules: [
      {
        userAgent: "*",
        allow: "/",
        disallow: [...DISALLOWED_PATHS],
      },
    ],
    sitemap: `${SITE_URL}/sitemap.xml`,
    host: SITE_URL,
  };
}
